# Generated by Django 3.2.5 on 2023-04-28 03:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('user', '0001_initial'),
        ('solicitudes', '0002_auto_20230427_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Viatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=6, null=True, unique=True)),
                ('montos_asignados', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('pagada', models.BooleanField(default=False)),
                ('autorizar', models.BooleanField(default=None, null=True)),
                ('autorizar2', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateField(null=True)),
                ('created_at_time', models.TimeField(null=True)),
                ('fecha_partida', models.DateField(null=True)),
                ('fecha_retorno', models.DateField(null=True)),
                ('lugar_partida', models.CharField(max_length=20, null=True)),
                ('lugar_comision', models.CharField(max_length=20, null=True)),
                ('transporte', models.CharField(max_length=40, null=True)),
                ('hospedaje', models.BooleanField(default=False)),
                ('comentario', models.TextField(max_length=200, null=True)),
                ('approved_at', models.DateField(null=True)),
                ('approved_at_time', models.TimeField(null=True)),
                ('approbado_fecha2', models.DateField(null=True)),
                ('approved_at_time2', models.TimeField(null=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Colaborador_viatico', to='user.profile')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.proyecto')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Crea_Viatico', to='user.profile')),
                ('subproyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.subproyecto')),
                ('superintendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autorizacion', to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Concepto_Viatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=75, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True)),
                ('precio', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('rendimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(decimal_places=6, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura_pdf', models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('factura_xml', models.FileField(blank=True, null=True, upload_to='xml', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('completo', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('viatico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viaticos.solicitud_viatico')),
            ],
            options={
                'unique_together': {('viatico', 'producto')},
            },
        ),
    ]
