# Generated by Django 3.2.5 on 2023-05-01 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('viaticos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud_viatico',
            old_name='approbado_fecha2',
            new_name='approved_at2',
        ),
        migrations.RemoveField(
            model_name='concepto_viatico',
            name='factura_pdf',
        ),
        migrations.RemoveField(
            model_name='concepto_viatico',
            name='factura_xml',
        ),
        migrations.CreateModel(
            name='Viaticos_Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subido', models.DateField(null=True)),
                ('hora_subido', models.TimeField(null=True)),
                ('comentario', models.CharField(blank=True, max_length=20, null=True)),
                ('hecho', models.BooleanField(default=False)),
                ('factura_pdf', models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('factura_xml', models.FileField(blank=True, null=True, upload_to='xml', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('concepto_viatico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viaticos.concepto_viatico')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
