# Generated by Django 4.2.9 on 2024-06-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0004_alter_concepto_viatico_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_viatico',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
