# Generated by Django 4.2.8 on 2024-06-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0005_alter_solicitud_viatico_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_viatico',
            name='comentarios_cancelacion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='solicitud_viatico',
            name='motivo',
            field=models.TextField(null=True),
        ),
    ]
