# Generated by Django 4.2.8 on 2024-06-20 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tipo_perfil_productos'),
        ('viaticos', '0006_solicitud_viatico_comentarios_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_viatico',
            name='gerente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AutorizacionG', to='user.profile'),
        ),
    ]
