# Generated by Django 4.2.15 on 2024-11-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0007_solicitud_viatico_gerente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_viatico',
            name='viatico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='viaticos.solicitud_viatico'),
        ),
        migrations.AlterField(
            model_name='viaticos_factura',
            name='concepto_viatico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='viaticos.concepto_viatico'),
        ),
    ]
