# Generated by Django 5.2.4 on 2026-03-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0008_alter_concepto_viatico_viatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaticos_factura',
            name='fecha_timbrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaticos_factura',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
