# Generated by Django 3.2.5 on 2023-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='viatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='viatico',
            field=models.BooleanField(default=False),
        ),
    ]
