# Generated by Django 3.2.5 on 2023-03-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='gasto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gasto',
            field=models.BooleanField(default=False),
        ),
    ]
