# Generated by Django 3.2.5 on 2022-03-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220323_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulosordenados',
            old_name='Producto',
            new_name='producto',
        ),
    ]
