# Generated by Django 3.2.5 on 2023-05-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230503_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulosordenados',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='articulosparasurtir',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='articulosparasurtir',
            name='cantidad_requisitar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='historicalarticulosparasurtir',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='historicalarticulosparasurtir',
            name='cantidad_requisitar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
