# Generated by Django 3.2.5 on 2022-09-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_subfamilia_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventario',
            name='cantidad_entradas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad_entradas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
