# Generated by Django 3.2.5 on 2023-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230323_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='estante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='estante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
