# Generated by Django 3.2.5 on 2022-03-23 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
        ('dashboard', '0003_rename_producto_articulosordenados_producto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto', 'distrito')},
        ),
    ]
