# Generated by Django 3.2.5 on 2023-03-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230331_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='estante',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='estante',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='historicalinventario',
            name='estante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalinventario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='estante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
