# Generated by Django 3.2.5 on 2023-05-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230511_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='nombre',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
