# Generated by Django 3.2.5 on 2022-09-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20220905_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulosparasurtir',
            old_name='selecionado',
            new_name='seleccionado',
        ),
        migrations.RenameField(
            model_name='historicalarticulosparasurtir',
            old_name='selecionado',
            new_name='seleccionado',
        ),
    ]
