# Generated by Django 3.2.5 on 2023-04-01 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tipo_perfil_calidad'),
        ('dashboard', '0005_auto_20230331_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='distrito',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.distrito'),
        ),
        migrations.AddField(
            model_name='order',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto', 'almacen')},
        ),
    ]
