# Generated by Django 3.2.5 on 2023-08-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_articulosordenados_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventario',
            name='activo_disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='activo_disponible',
            field=models.BooleanField(default=False),
        ),
    ]
