# Generated by Django 4.2.4 on 2023-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20230810_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalarticulosparasurtir',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical articulospara surtir', 'verbose_name_plural': 'historical articulospara surtirs'},
        ),
        migrations.AlterModelOptions(
            name='historicalinventario',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical inventario', 'verbose_name_plural': 'historical inventarios'},
        ),
        migrations.AlterModelOptions(
            name='historicalorder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical order', 'verbose_name_plural': 'historical orders'},
        ),
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical product', 'verbose_name_plural': 'historical products'},
        ),
        migrations.AlterField(
            model_name='historicalarticulosparasurtir',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinventario',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subfamilia',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
