# Generated by Django 3.2.5 on 2023-04-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20230413_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosparasurtir',
            name='comentario',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticulosparasurtir',
            name='comentario',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
