# Generated by Django 3.2.5 on 2022-03-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        ('dashboard', '0009_auto_20220324_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='activo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.activo'),
        ),
        migrations.AddField(
            model_name='order',
            name='operacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.operacion'),
        ),
        migrations.AddField(
            model_name='order',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.proyecto'),
        ),
        migrations.AddField(
            model_name='order',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.sector'),
        ),
        migrations.AddField(
            model_name='order',
            name='subproyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.subproyecto'),
        ),
    ]
