# Generated by Django 4.2.4 on 2023-09-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_banco_nombre'),
        ('dashboard', '0010_alter_familia_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creador', to='user.profile')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comentario_articulo', models.TextField(blank=True, null=True)),
                ('comentario_plantilla', models.TextField(blank=True, null=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('plantilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.plantilla')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario')),
            ],
        ),
    ]
