# Generated by Django 4.2.9 on 2024-01-29 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_banco_nombre'),
        ('dashboard', '0011_plantilla_articuloplantilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criticidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grado_Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='codigo',
            field=models.CharField(db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Producto_Calidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('especs', models.TextField(blank=True, null=True)),
                ('documentacion', models.TextField(blank=True, null=True)),
                ('criterios_aceptacion', models.TextField(blank=True, null=True)),
                ('documental', models.BooleanField(default=False)),
                ('inspeccion', models.BooleanField(default=False)),
                ('cumplimiento', models.BooleanField(default=False)),
                ('g_cumplimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cumplimiento', to='dashboard.grado_control')),
                ('g_documental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documental', to='dashboard.grado_control')),
                ('g_inspeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion', to='dashboard.grado_control')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='critico',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.criticidad'),
        ),
        migrations.AddField(
            model_name='product',
            name='critico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.criticidad'),
        ),
    ]
