# Generated by Django 3.2.5 on 2022-03-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_order_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='folio',
        ),
    ]
