# Generated by Django 4.2.4 on 2023-10-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_plantilla_articuloplantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='codigo',
            field=models.CharField(db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
