# Generated by Django 4.2.9 on 2024-01-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_criticidad_grado_control_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_calidad',
            old_name='criterios_aceptacion',
            new_name='requisitos',
        ),
        migrations.RemoveField(
            model_name='producto_calidad',
            name='documentacion',
        ),
        migrations.RemoveField(
            model_name='producto_calidad',
            name='especs',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='especs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='especs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
