# Generated by Django 4.2.9 on 2024-01-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_criterios_aceptacion_producto_calidad_requisitos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='rev_calidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rev_calidad',
            field=models.BooleanField(default=False),
        ),
    ]
