# Generated by Django 3.2.5 on 2022-04-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_order_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.familia'),
        ),
    ]
