# Generated by Django 3.2.5 on 2022-04-06 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_marca_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='autorizar',
            field=models.BooleanField(default=False),
        ),
    ]
