# Generated by Django 4.2.9 on 2024-01-31 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_producto_calidad_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_calidad',
            name='producto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_calidad', to='dashboard.product'),
        ),
    ]
