# Generated by Django 3.2.5 on 2022-04-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_order_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
