# Generated by Django 5.0.1 on 2024-02-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_historicalproduct_codigo_alter_product_codigo'),
        ('dashboard', '0016_alter_producto_calidad_producto'),
    ]

    operations = [
    ]
