# Generated by Django 3.2.5 on 2022-04-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_order_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='autorizar',
            field=models.BooleanField(null=True),
        ),
    ]
