# Generated by Django 4.2.9 on 2024-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_merge_20240204_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='criterios_aceptacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='descripcion_especifica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='criterios_aceptacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion_especifica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
