# Generated by Django 4.2.9 on 2024-03-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_historicalproduct_criterios_aceptacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='preevaluacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preevaluacion',
            field=models.BooleanField(default=True),
        ),
    ]
