# Generated by Django 4.2.9 on 2024-03-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_historicalproduct_preevaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='preevaluacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='preevaluacion',
            field=models.BooleanField(default=False),
        ),
    ]
