# Generated by Django 3.2.5 on 2022-04-15 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_order_autorizar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='order',
            name='approved_at_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='approved_at_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
