# Generated by Django 4.2.9 on 2024-05-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_historicalproduct_preevaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='preciomax',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preciomax',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
