# Generated by Django 3.2.5 on 2022-04-15 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20220415_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approved_at_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='approved_at_time',
        ),
        migrations.AddField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
