# Generated by Django 4.2.8 on 2024-06-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_historicalproduct_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_calidad',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
