# Generated by Django 3.2.5 on 2022-04-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20220418_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticulosparaSurtir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('articulos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.articulosordenados')),
            ],
        ),
    ]
