# Generated by Django 4.2.15 on 2024-08-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_articulosordenados_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='caducidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='caducidad',
            field=models.BooleanField(default=False),
        ),
    ]
