# Generated by Django 3.2.5 on 2022-04-18 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_image'),
        ('dashboard', '0023_articulosparasurtir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sol_autorizada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autoriza', to='user.profile'),
        ),
    ]
