# Generated by Django 4.2.15 on 2024-12-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_historicalproduct_caducidad_product_caducidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='fecha_criticidad',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fecha_criticidad',
            field=models.DateTimeField(null=True),
        ),
    ]
