# Generated by Django 4.2.15 on 2024-12-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_delete_activo'),
        ('user', '0007_tipo_perfil_activos'),
        ('dashboard', '0025_historicalproduct_fecha_criticidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Producto_Terminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('complete', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('comentario', models.TextField(blank=True, max_length=200, null=True)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.proyecto')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('subproyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.subproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Solicitud_Terminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20, null=True, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, max_length=100, null=True)),
                ('complete', models.BooleanField(null=True)),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='dashboard.productos_solicitud_terminado')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario')),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='dashboard.solicitud_producto_terminado')),
            ],
        ),
    ]
