# Generated by Django 3.2.5 on 2022-04-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_order_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosparasurtir',
            name='surtir',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
