# Generated by Django 4.2.15 on 2024-12-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tipo_perfil_activos'),
        ('dashboard', '0026_solicitud_producto_terminado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_producto_terminado',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creo_solicitud', to='user.profile'),
        ),
    ]
