# Generated by Django 3.2.5 on 2022-04-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_articulosparasurtir_surtir'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='apartado',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
