# Generated by Django 3.2.5 on 2022-04-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_inventario_apartado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='apartado',
        ),
        migrations.AddField(
            model_name='articulosparasurtir',
            name='cantidad_requisitar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='articulosparasurtir',
            name='requisitar',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
