# Generated by Django 4.2.15 on 2024-12-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_productos_solicitud_terminado_validado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_producto_terminado',
            name='concluida',
            field=models.BooleanField(null=True),
        ),
    ]
