# Generated by Django 4.2.15 on 2025-01-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_solicitud_producto_terminado_concluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_solicitud_terminado',
            name='cliente',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productos_solicitud_terminado',
            name='destino',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
