# Generated by Django 4.2.9 on 2025-03-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_productos_solicitud_terminado_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventario',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
