# Generated by Django 5.2.4 on 2025-10-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_historicalinventario_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='folio',
            field=models.CharField(db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='folio',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
