# Generated by Django 3.2.5 on 2022-04-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20220421_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosparasurtir',
            name='salida',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
