# Generated by Django 5.2.4 on 2026-02-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_historicalorder_folio_alter_order_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_solicitud_terminado',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
