# Generated by Django 5.2.4 on 2026-02-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_productos_solicitud_terminado_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosordenados',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
