# Generated by Django 3.2.5 on 2022-04-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_articulosparasurtir_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosparasurtir',
            name='cantidad_salida',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
