# Generated by Django 5.2.4 on 2026-02-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_articulosordenados_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosordenados',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
