# Generated by Django 3.2.5 on 2022-04-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20220425_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulosparasurtir',
            name='material_recibido_por',
        ),
        migrations.RemoveField(
            model_name='historicalarticulosparasurtir',
            name='material_recibido_por',
        ),
    ]
