# Generated by Django 3.2.5 on 2022-05-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20220425_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requisitar',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
