# Generated by Django 3.2.5 on 2022-06-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_historicalinventario_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventario',
            name='cantidad_apartada',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cantidad_apartada',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
