# Generated by Django 3.2.5 on 2022-06-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20220622_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at_time',
        ),
    ]
