# Generated by Django 3.2.5 on 2022-06-22 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_remove_order_created_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
