# Generated by Django 3.2.5 on 2022-06-22 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_order_created_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosparasurtir',
            name='created_at_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalarticulosparasurtir',
            name='created_at_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulosparasurtir',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulosparasurtir',
            name='created_at',
            field=models.DateField(blank=True, editable=False),
        ),
    ]
