# Generated by Django 3.2.5 on 2022-06-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20220622_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulosparasurtir',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulosparasurtir',
            name='modified_at',
            field=models.DateField(blank=True, editable=False),
        ),
    ]
