# Generated by Django 3.2.5 on 2022-06-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20220622_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='approved_at_time',
            field=models.TimeField(),
        ),
    ]
