# Generated by Django 3.2.5 on 2022-06-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20220622_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventario',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
