# Generated by Django 3.2.5 on 2022-06-24 03:43

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20220623_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventario',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14),
        ),
    ]
