# Generated by Django 3.2.5 on 2022-07-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_historicalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
