# Generated by Django 3.2.5 on 2022-07-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_auto_20220711_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='approved_at_time',
            field=models.TimeField(null=True),
        ),
    ]
