# Generated by Django 3.2.5 on 2022-07-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20220713_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventario',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
