# Generated by Django 3.2.5 on 2022-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_auto_20220718_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventario',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
