# Generated by Django 3.2.5 on 2022-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_auto_20220718_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='surtida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='surtida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articulosparasurtir',
            name='surtir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalarticulosparasurtir',
            name='surtir',
            field=models.BooleanField(default=False),
        ),
    ]
