# Generated by Django 3.2.5 on 2022-08-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_auto_20220817_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventario',
            name='minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventario',
            name='minimo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
