# Generated by Django 3.2.5 on 2022-08-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_auto_20220821_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sector',
        ),
    ]
