# Generated by Django 3.2.5 on 2022-09-01 18:11

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_auto_20220822_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosparasurtir',
            name='precio',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14),
        ),
        migrations.AddField(
            model_name='articulosparasurtir',
            name='precio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='historicalarticulosparasurtir',
            name='precio',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14),
        ),
        migrations.AddField(
            model_name='historicalarticulosparasurtir',
            name='precio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
    ]
