# Generated by Django 3.2.5 on 2022-09-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20220901_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventario',
            name='entrada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='entrada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
