# Generated by Django 3.2.5 on 2022-04-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0022_auto_20220418_1332'),
        ('user', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autorizar', models.BooleanField(default=None, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.order')),
                ('requi_autorizada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ArticulosRequisitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario')),
                ('req', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.requis')),
            ],
        ),
    ]
