# Generated by Django 3.2.5 on 2023-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulosrequisitados',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='articulosrequisitados',
            name='cantidad_comprada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='historicalarticulosrequisitados',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='historicalarticulosrequisitados',
            name='cantidad_comprada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='historicalsalidas',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
