# Generated by Django 3.2.5 on 2022-09-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220902_1816'),
        ('user', '0001_initial'),
        ('requisiciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsalidas',
            name='almacenista',
        ),
        migrations.RemoveField(
            model_name='salidas',
            name='almacenista',
        ),
        migrations.CreateModel(
            name='ValeSalidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('almacenista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Almacen', to='user.profile')),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.order')),
            ],
        ),
        migrations.AddField(
            model_name='historicalsalidas',
            name='vale_salida',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requisiciones.valesalidas'),
        ),
        migrations.AddField(
            model_name='salidas',
            name='vale_salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.valesalidas'),
        ),
    ]
