# Generated by Django 3.2.5 on 2022-04-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20220421_1027'),
        ('requisiciones', '0002_alter_requis_approved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.articulosparasurtir')),
            ],
        ),
    ]
