# Generated by Django 3.2.5 on 2022-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0002_auto_20220905_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valesalidas',
            old_name='orden',
            new_name='solicitud',
        ),
        migrations.AddField(
            model_name='valesalidas',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='valesalidas',
            name='firmado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
