# Generated by Django 3.2.5 on 2022-04-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0003_salidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
