# Generated by Django 3.2.5 on 2023-05-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0003_devolucion_devolucion_articulos_historicaldevolucion_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion_articulos',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevolucion_articulos',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
