# Generated by Django 3.2.5 on 2022-09-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('requisiciones', '0003_auto_20220905_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsalidas',
            name='material_recibido_por',
        ),
        migrations.RemoveField(
            model_name='salidas',
            name='material_recibido_por',
        ),
        migrations.AddField(
            model_name='valesalidas',
            name='material_recibido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vale', to='user.profile'),
        ),
    ]
