# Generated by Django 3.2.5 on 2022-09-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0004_auto_20220905_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalidas',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='salidas',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
