# Generated by Django 3.2.5 on 2023-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0004_auto_20230516_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion_articulos',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaldevolucion_articulos',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
