# Generated by Django 3.2.5 on 2022-04-22 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_image'),
        ('requisiciones', '0004_alter_salidas_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidas',
            name='almacenista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Almacen', to='user.profile'),
        ),
    ]
