# Generated by Django 3.2.5 on 2022-09-07 00:06

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0005_auto_20220906_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalidas',
            name='entrada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalidas',
            name='precio',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14),
        ),
        migrations.AddField(
            model_name='historicalsalidas',
            name='precio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='salidas',
            name='entrada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salidas',
            name='precio',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14),
        ),
        migrations.AddField(
            model_name='salidas',
            name='precio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
    ]
