# Generated by Django 3.2.5 on 2022-04-22 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0005_salidas_almacenista'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosrequisitados',
            name='salida',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='salidas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
