# Generated by Django 3.2.5 on 2023-05-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0005_auto_20230523_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosrequisitados',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulosrequisitados',
            name='comentario_cancelacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticulosrequisitados',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalarticulosrequisitados',
            name='comentario_cancelacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
