# Generated by Django 3.2.5 on 2023-05-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_auto_20230427_2137'),
        ('requisiciones', '0006_auto_20230524_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valesalidas',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.proyecto'),
        ),
        migrations.AlterField(
            model_name='valesalidas',
            name='subproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.subproyecto'),
        ),
    ]
