# Generated by Django 3.2.5 on 2022-04-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0006_auto_20220422_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulosrequisitados',
            name='salida',
        ),
    ]
