# Generated by Django 3.2.5 on 2022-04-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0007_remove_articulosrequisitados_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidas',
            name='cantidad_parcial',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
