# Generated by Django 3.2.5 on 2022-04-23 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0008_salidas_cantidad_parcial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidas',
            name='cantidad_parcial',
        ),
    ]
