# Generated by Django 3.2.5 on 2023-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0008_auto_20230622_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='autorizada',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
