# Generated by Django 3.2.5 on 2023-08-05 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0009_devolucion_autorizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='devolucion',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.salidas'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.tipo_devolucion'),
        ),
    ]
