# Generated by Django 3.2.5 on 2022-04-25 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_image'),
        ('requisiciones', '0010_historicalsalidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalidas',
            name='material_recibido_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
        migrations.AddField(
            model_name='salidas',
            name='material_recibido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Salidas', to='user.profile'),
        ),
    ]
