# Generated by Django 3.2.5 on 2022-05-02 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20220425_1619'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_tipo_perfil_crear_sol'),
        ('requisiciones', '0012_auto_20220425_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosrequisitados',
            name='almacenista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Almacen2', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='articulosrequisitados',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.articulosparasurtir'),
        ),
        migrations.CreateModel(
            name='HistoricalArticulosRequisitados',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('almacenista', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.articulosparasurtir')),
                ('req', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requisiciones.requis')),
            ],
            options={
                'verbose_name': 'historical articulos requisitados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
