# Generated by Django 4.2.8 on 2024-03-27 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_merge_20240204_1331'),
        ('requisiciones', '0012_alter_historicalarticulosrequisitados_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requis',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requis', to='dashboard.order'),
        ),
        migrations.AlterField(
            model_name='valesalidas',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vale_salida', to='dashboard.order'),
        ),
    ]
