# Generated by Django 4.2.8 on 2024-04-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0013_alter_requis_orden_alter_valesalidas_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulosrequisitados',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='requisiciones.requis'),
        ),
    ]
