# Generated by Django 3.2.5 on 2022-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0013_auto_20220502_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='requis',
            name='colocada',
            field=models.BooleanField(null=True),
        ),
    ]
