# Generated by Django 4.2.15 on 2024-12-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0014_alter_articulosrequisitados_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='valesalidas',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
