# Generated by Django 3.2.5 on 2022-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0014_requis_colocada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requis',
            name='colocada',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
