# Generated by Django 3.2.5 on 2022-05-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0015_alter_requis_colocada'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosrequisitados',
            name='cantidad_comprada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticulosrequisitados',
            name='cantidad_comprada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
