# Generated by Django 4.2.15 on 2024-12-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0015_valesalidas_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valesalidas',
            name='referencia',
        ),
        migrations.AddField(
            model_name='historicalsalidas',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salidas',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
