# Generated by Django 3.2.5 on 2022-05-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0016_auto_20220524_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosrequisitados',
            name='art_surtido',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticulosrequisitados',
            name='art_surtido',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
