# Generated by Django 4.2.15 on 2024-12-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0016_remove_valesalidas_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalidas',
            name='cliente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='salidas',
            name='cliente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
