# Generated by Django 4.2.15 on 2024-12-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_historicalproduct_fecha_criticidad_and_more'),
        ('requisiciones', '0017_historicalsalidas_cliente_salidas_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.articulosparasurtir'),
        ),
        migrations.AlterField(
            model_name='valesalidas',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vale_salida', to='dashboard.order'),
        ),
    ]
