# Generated by Django 3.2.5 on 2022-05-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0017_auto_20220524_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requis',
            name='colocada',
            field=models.BooleanField(default=False),
        ),
    ]
