# Generated by Django 4.2.15 on 2024-12-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_solicitud_producto_terminado_and_more'),
        ('requisiciones', '0018_alter_salidas_producto_alter_valesalidas_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalidas',
            name='producto_terminado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.productos_solicitud_terminado'),
        ),
        migrations.AddField(
            model_name='salidas',
            name='producto_terminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.productos_solicitud_terminado'),
        ),
        migrations.AddField(
            model_name='valesalidas',
            name='solicitud_terminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vale_salida_terminado', to='dashboard.productos_solicitud_terminado'),
        ),
    ]
