# Generated by Django 3.2.5 on 2022-07-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0019_auto_20220627_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requis',
            name='approved_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='requis',
            name='approved_at_time',
            field=models.TimeField(null=True),
        ),
    ]
