# Generated by Django 4.2.15 on 2024-12-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_solicitud_producto_terminado_and_more'),
        ('requisiciones', '0019_historicalsalidas_producto_terminado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valesalidas',
            name='solicitud_terminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vale_salida_terminado', to='dashboard.solicitud_producto_terminado'),
        ),
    ]
