# Generated by Django 4.2.15 on 2025-01-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0020_alter_valesalidas_solicitud_terminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion_articulos',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaldevolucion_articulos',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
