# Generated by Django 5.2.4 on 2025-11-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0021_devolucion_articulos_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion_articulos',
            name='vale_devolucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucion_articulos', to='requisiciones.devolucion'),
        ),
    ]
