# Generated by Django 3.2.5 on 2022-07-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0021_auto_20220713_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulosrequisitados',
            name='sel_comp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalarticulosrequisitados',
            name='sel_comp',
            field=models.BooleanField(default=False),
        ),
    ]
