# Generated by Django 5.2.4 on 2026-02-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0022_alter_devolucion_articulos_vale_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='valesalidas',
            name='cliente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='valesalidas',
            name='destino',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
