# Generated by Django 3.2.5 on 2022-09-02 02:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=13, null=True)),
                ('clabe', models.CharField(max_length=22, null=True)),
                ('monto_inicial_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3)),
                ('monto_inicial', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True)),
                ('saldo_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3)),
                ('saldo', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.banco')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito')),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3)),
                ('monto', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MXN', max_digits=14)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('pagado_date', models.DateField(blank=True, null=True)),
                ('pagado_hora', models.TimeField(blank=True, null=True)),
                ('hecho', models.BooleanField(default=False)),
                ('tipo_de_cambio_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3)),
                ('tipo_de_cambio', djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='MXN', max_digits=14, null=True)),
                ('comprobante_pago', models.FileField(null=True, upload_to='comprobante', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesoreria.cuenta')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito')),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('tesorero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tesorero', to='user.profile')),
            ],
        ),
    ]
