# Generated by Django 3.2.5 on 2023-05-01 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0002_auto_20230501_1414'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='viatico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viaticos.solicitud_viatico'),
        ),
    ]
