# Generated by Django 3.2.5 on 2022-06-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='hecho_por',
            new_name='tesorero',
        ),
    ]
