# Generated by Django 3.2.5 on 2023-04-06 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_pago_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subido', models.DateField(blank=True, null=True)),
                ('hora_subido', models.TimeField(blank=True, null=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('hecho', models.BooleanField(default=False)),
                ('factura_pdf', models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('factura_xml', models.FileField(blank=True, null=True, upload_to='xml', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesoreria.pago')),
            ],
        ),
    ]
