# Generated by Django 3.2.5 on 2022-06-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tipo_perfil_crear_sol'),
        ('tesoreria', '0002_rename_hecho_por_pago_tesorero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito'),
        ),
    ]
