# Generated by Django 3.2.5 on 2022-06-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0004_alter_pago_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='saldo',
            new_name='pagado',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='saldo_currency',
            new_name='pagado_currency',
        ),
    ]
