# Generated by Django 3.2.5 on 2022-06-03 23:38

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0005_auto_20220603_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='pagado',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14),
        ),
    ]
