# Generated by Django 3.2.5 on 2023-05-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0005_alter_pago_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo_de_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True),
        ),
    ]
