# Generated by Django 3.2.5 on 2023-05-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0006_alter_pago_tipo_de_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo_de_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
