# Generated by Django 3.2.5 on 2022-06-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0007_pago_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='pagado',
            new_name='monto_pagado',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='pagado_currency',
            new_name='monto_pagado_currency',
        ),
    ]
