# Generated by Django 3.2.5 on 2022-06-06 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0008_auto_20220603_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobante', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
