# Generated by Django 3.2.5 on 2022-06-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0009_pago_comprobante_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='pagada',
        ),
    ]
