# Generated by Django 4.2.9 on 2024-06-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0016_alter_articulo_gasto_producto'),
        ('viaticos', '0005_alter_solicitud_viatico_comentario'),
        ('compras', '0041_alter_item_comparativo_comparativo_and_more'),
        ('tesoreria', '0009_alter_pago_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagosg', to='gastos.solicitud_gasto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.compra'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='viatico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagosv', to='viaticos.solicitud_viatico'),
        ),
    ]
