# Generated by Django 4.2.15 on 2024-09-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0010_alter_pago_gasto_alter_pago_oc_alter_pago_viatico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
