# Generated by Django 3.2.5 on 2022-06-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0010_remove_pago_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pagado_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagado_hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
