# Generated by Django 4.2.8 on 2025-07-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0011_alter_cuenta_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pagado_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
