# Generated by Django 3.2.5 on 2022-06-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0011_auto_20220606_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
