# Generated by Django 5.2.4 on 2026-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0012_pago_pagado_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
