# Generated by Django 3.2.5 on 2022-06-07 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0013_alter_pago_pagado_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante_pago',
            field=models.FileField(null=True, upload_to='comprobante', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
