# Generated by Django 5.2.4 on 2026-03-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0013_facturas_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fecha_timbrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
