# Generated by Django 3.2.5 on 2022-06-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0016_alter_pago_monto_pagado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='monto_pagado',
            new_name='monto',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='monto_pagado_currency',
            new_name='monto_currency',
        ),
    ]
