# Generated by Django 3.2.5 on 2022-07-08 18:16

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0019_alter_pago_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo_de_cambio',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='MXN', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_de_cambio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
    ]
