# Generated by Django 3.2.5 on 2022-07-09 00:02

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0020_auto_20220708_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo_de_cambio',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='MXN', max_digits=14, null=True),
        ),
    ]
