# Generated by Django 3.2.5 on 2022-09-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaarticulo',
            name='agotado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entradaarticulo',
            name='cantidad_por_surtir',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='agotado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='cantidad_por_surtir',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
