# Generated by Django 3.2.5 on 2023-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaarticulo',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
