# Generated by Django 3.2.5 on 2022-06-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_auto_20220613_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaarticulo',
            name='articulo_entregado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='articulo_entregado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
