# Generated by Django 3.2.5 on 2023-08-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0004_historicalnc_articulo_historicalno_conformidad_nc_articulo_no_conformidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaarticulo',
            name='cantidad_por_surtir',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='historicalentradaarticulo',
            name='cantidad_por_surtir',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
