# Generated by Django 3.2.5 on 2022-07-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_auto_20220621_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaarticulo',
            name='articulo_entregado',
        ),
        migrations.RemoveField(
            model_name='historicalentradaarticulo',
            name='articulo_entregado',
        ),
    ]
