# Generated by Django 3.2.5 on 2023-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_auto_20230817_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaarticulo',
            name='cantidad_por_surtir',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentradaarticulo',
            name='cantidad_por_surtir',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
