# Generated by Django 4.2.9 on 2024-01-29 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0008_resultado_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_calidad',
            name='evaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.resultado_evaluacion'),
        ),
    ]
