# Generated by Django 4.2.9 on 2024-01-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0009_alter_reporte_calidad_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado_evaluacion',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
