# Generated by Django 5.0.1 on 2024-02-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0011_entradaarticulo_fecha_recepcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaarticulo',
            name='almacenado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='almacenado',
            field=models.BooleanField(default=False),
        ),
    ]
