# Generated by Django 5.0.1 on 2024-02-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0012_entradaarticulo_almacenado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaarticulo',
            name='entrada_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='entrada_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
