# Generated by Django 4.2.8 on 2024-03-27 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0040_alter_compra_req'),
        ('entradas', '0013_entradaarticulo_entrada_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vale_entrada', to='compras.compra'),
        ),
    ]
