# Generated by Django 4.2.8 on 2024-04-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0014_alter_entrada_oc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaarticulo',
            name='entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='entradas.entrada'),
        ),
    ]
