# Generated by Django 4.2.15 on 2024-08-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0015_alter_entradaarticulo_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre_Nc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Nc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalno_conformidad',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalno_conformidad',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='no_conformidad',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='no_conformidad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='calidad'),
        ),
        migrations.AddField(
            model_name='historicalno_conformidad',
            name='cierre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entradas.cierre_nc'),
        ),
        migrations.AddField(
            model_name='historicalno_conformidad',
            name='tipo_nc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entradas.tipo_nc'),
        ),
        migrations.AddField(
            model_name='no_conformidad',
            name='cierre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.cierre_nc'),
        ),
        migrations.AddField(
            model_name='no_conformidad',
            name='tipo_nc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.tipo_nc'),
        ),
    ]
