# Generated by Django 4.2.15 on 2024-08-30 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0043_historicalpreevaluacion_eval_actividades_and_more'),
        ('entradas', '0016_cierre_nc_tipo_nc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaarticulo',
            name='articulo_comprado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_articulos', to='compras.articulocomprado'),
        ),
    ]
