# Generated by Django 4.2.15 on 2024-08-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0018_alter_entradaarticulo_articulo_comprado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnc_articulo',
            name='entrada_articulo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entradas.entradaarticulo'),
        ),
        migrations.AddField(
            model_name='nc_articulo',
            name='entrada_articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nc_articulos', to='entradas.entradaarticulo'),
        ),
    ]
