# Generated by Django 4.2.15 on 2024-09-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0019_historicalnc_articulo_entrada_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nc_articulo',
            name='entrada_articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nc_articulos', to='entradas.entradaarticulo'),
        ),
    ]
