# Generated by Django 4.2.15 on 2024-09-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0020_alter_nc_articulo_entrada_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnc_articulo',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nc_articulo',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
