# Generated by Django 4.2.15 on 2024-09-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0021_historicalnc_articulo_resuelto_nc_articulo_resuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaarticulo',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
