# Generated by Django 4.2.15 on 2024-09-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0022_entradaarticulo_fecha_caducidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaarticulo',
            name='calidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='calidad',
            field=models.BooleanField(default=False),
        ),
    ]
