# Generated by Django 4.2.15 on 2024-09-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0023_entradaarticulo_calidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte_calidad',
            name='evaluacion',
        ),
        migrations.AddField(
            model_name='reporte_calidad',
            name='autorizado',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Resultado_Evaluacion',
        ),
    ]
