# Generated by Django 4.2.15 on 2024-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0024_remove_reporte_calidad_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_calidad',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
    ]
