# Generated by Django 4.2.15 on 2024-09-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0025_alter_reporte_calidad_autorizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_calidad',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_calidad', to='entradas.entradaarticulo'),
        ),
    ]
