# Generated by Django 4.2.15 on 2024-12-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0044_alter_preevaluacion_comparativo_model'),
        ('dashboard', '0025_historicalproduct_fecha_criticidad_and_more'),
        ('solicitudes', '0009_delete_activo'),
        ('user', '0007_tipo_perfil_activos'),
        ('entradas', '0026_alter_reporte_calidad_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vale_entrada', to='compras.compra'),
        ),
        migrations.CreateModel(
            name='Solicitud_Producto_Terminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=6, null=True, unique=True)),
                ('folio', models.IntegerField(null=True)),
                ('complete', models.BooleanField(null=True)),
                ('created_at', models.DateField(null=True)),
                ('comentario', models.TextField(blank=True, max_length=200, null=True)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.proyecto')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('subproyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.subproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Solicitud_Terminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, max_length=100, null=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario')),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='entradas.solicitud_producto_terminado')),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soliciutd_entrada', to='entradas.solicitud_producto_terminado'),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='solicitud',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entradas.solicitud_producto_terminado'),
        ),
    ]
