# Generated by Django 4.2.15 on 2024-12-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0027_alter_entrada_oc_solicitud_producto_terminado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_producto_terminado',
            name='serie',
        ),
        migrations.AddField(
            model_name='productos_solicitud_terminado',
            name='serie',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
