# Generated by Django 4.2.15 on 2024-12-23 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0028_remove_solicitud_producto_terminado_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_producto_terminado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
