# Generated by Django 4.2.15 on 2024-12-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0030_alter_solicitud_producto_terminado_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_producto_terminado',
            name='folio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
