# Generated by Django 4.2.15 on 2024-12-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0031_alter_solicitud_producto_terminado_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_solicitud_terminado',
            name='serie',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
