# Generated by Django 4.2.15 on 2024-12-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0032_alter_productos_solicitud_terminado_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_solicitud_terminado',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='entradas.productos_solicitud_terminado'),
        ),
    ]
