# Generated by Django 4.2.15 on 2024-12-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0033_productos_solicitud_terminado_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_solicitud_terminado',
            name='complete',
            field=models.BooleanField(null=True),
        ),
    ]
