# Generated by Django 4.2.15 on 2024-12-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0044_alter_preevaluacion_comparativo_model'),
        ('user', '0007_tipo_perfil_activos'),
        ('entradas', '0034_productos_solicitud_terminado_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_producto_terminado',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito'),
        ),
        migrations.AlterField(
            model_name='entradaarticulo',
            name='articulo_comprado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.articulocomprado'),
        ),
    ]
