# Generated by Django 4.2.15 on 2024-12-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0035_solicitud_producto_terminado_distrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_producto_terminado',
            name='distrito',
        ),
    ]
