# Generated by Django 4.2.15 on 2024-12-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0036_remove_solicitud_producto_terminado_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaarticulo',
            name='producto_terminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entradas.productos_solicitud_terminado'),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='producto_terminado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entradas.productos_solicitud_terminado'),
        ),
    ]
