# Generated by Django 4.2.15 on 2024-12-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0037_entradaarticulo_producto_terminado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='entradaarticulo',
            name='producto_terminado',
        ),
        migrations.RemoveField(
            model_name='historicalentrada',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='historicalentradaarticulo',
            name='producto_terminado',
        ),
    ]
