# Generated by Django 4.2.15 on 2024-12-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0038_remove_entrada_solicitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_producto_terminado',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='solicitud_producto_terminado',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='solicitud_producto_terminado',
            name='subproyecto',
        ),
        migrations.DeleteModel(
            name='Productos_Solicitud_Terminado',
        ),
        migrations.DeleteModel(
            name='Solicitud_Producto_Terminado',
        ),
    ]
