# Generated by Django 4.2.15 on 2024-12-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_solicitud_producto_terminado_and_more'),
        ('entradas', '0039_remove_solicitud_producto_terminado_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soliciutd_entrada', to='dashboard.solicitud_producto_terminado'),
        ),
        migrations.AddField(
            model_name='entradaarticulo',
            name='producto_terminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.productos_solicitud_terminado'),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='solicitud',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.solicitud_producto_terminado'),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='producto_terminado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.productos_solicitud_terminado'),
        ),
    ]
