# Generated by Django 5.2.4 on 2026-02-19 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_productos_solicitud_terminado_precio'),
        ('entradas', '0041_alter_entrada_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_entrada', to='dashboard.order'),
        ),
        migrations.AddField(
            model_name='entradaarticulo',
            name='articulo_terminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.articulosordenados'),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='orden',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.order'),
        ),
        migrations.AddField(
            model_name='historicalentradaarticulo',
            name='articulo_terminado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.articulosordenados'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soliciutd_entrada', to='dashboard.solicitud_producto_terminado'),
        ),
        migrations.AlterField(
            model_name='entradaarticulo',
            name='producto_terminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.productos_solicitud_terminado'),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='solicitud',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.solicitud_producto_terminado'),
        ),
        migrations.AlterField(
            model_name='historicalentradaarticulo',
            name='producto_terminado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.productos_solicitud_terminado'),
        ),
    ]
