# Generated by Django 5.2.4 on 2026-02-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0042_entrada_orden_entradaarticulo_articulo_terminado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='historicalentrada',
            name='solicitud',
        ),
    ]
