# Generated by Django 5.2.4 on 2026-02-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_articulosordenados_precio'),
        ('entradas', '0043_remove_entrada_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaarticulo',
            name='producto_terminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productos_solicitud_terminado'),
        ),
    ]
