# Generated by Django 5.2.4 on 2026-02-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0044_alter_entradaarticulo_producto_terminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte_calidad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='calidad'),
        ),
    ]
