# Generated by Django 3.2.5 on 2022-09-02 02:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito')),
            ],
            options={
                'unique_together': {('nombre', 'distrito')},
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
                ('presupuesto_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3)),
                ('presupuesto', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MXN', max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gastado_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3)),
                ('gastado', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_unidad', models.CharField(max_length=15, null=True, unique=True)),
                ('tipo', models.CharField(max_length=15, null=True)),
                ('serie', models.CharField(max_length=15, null=True)),
                ('cuenta', models.CharField(max_length=15, null=True)),
                ('factura_interna', models.CharField(max_length=15, null=True)),
                ('arrendado', models.BooleanField(default=True)),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito')),
            ],
        ),
    ]
