# Generated by Django 3.2.5 on 2022-05-07 01:05

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproyecto',
            name='presupuesto_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
    ]
