# Generated by Django 3.2.5 on 2023-08-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_auto_20230427_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
