# Generated by Django 4.2.8 on 2024-04-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_auto_20230810_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproyecto',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subproyecto',
            unique_together={('nombre', 'proyecto')},
        ),
    ]
