# Generated by Django 4.2.8 on 2024-04-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_alter_subproyecto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproyecto',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subproyectos', to='solicitudes.proyecto'),
        ),
    ]
