# Generated by Django 4.2.15 on 2024-09-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_subproyecto_proyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activo',
        ),
    ]
