# Generated by Django 4.2.15 on 2024-09-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tipo_perfil_activos'),
        ('solicitudes', '0007_delete_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_unidad', models.CharField(max_length=15, null=True, unique=True)),
                ('tipo', models.CharField(max_length=15, null=True)),
                ('serie', models.CharField(max_length=15, null=True)),
                ('cuenta', models.CharField(max_length=15, null=True)),
                ('factura_interna', models.CharField(max_length=15, null=True)),
                ('arrendado', models.BooleanField(default=True)),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito')),
            ],
        ),
    ]
