# Generated by Django 4.2.15 on 2024-09-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activo',
        ),
    ]
