# Generated by Django 5.2.4 on 2026-02-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_delete_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Subproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subproyecto',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.status_subproyecto'),
        ),
    ]
