# Generated by Django 3.2.5 on 2023-03-23 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('abreviado', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('inicio_estadisticas', models.BooleanField(default=False, null=True)),
                ('configuracion', models.BooleanField(default=False, null=True)),
                ('almacen', models.BooleanField(default=False, null=True)),
                ('solicitudes', models.BooleanField(default=False, null=True)),
                ('requisiciones', models.BooleanField(default=False, null=True)),
                ('compras', models.BooleanField(default=False, null=True)),
                ('tesoreria', models.BooleanField(default=False, null=True)),
                ('autorizacion', models.BooleanField(default=False, null=True)),
                ('reportes', models.BooleanField(default=False, null=True)),
                ('historicos', models.BooleanField(default=False, null=True)),
                ('supervisor', models.BooleanField(default=False, null=True)),
                ('superintendente', models.BooleanField(default=False, null=True)),
                ('almacenista', models.BooleanField(default=False, null=True)),
                ('comprador', models.BooleanField(default=False, null=True)),
                ('oc_superintendencia', models.BooleanField(default=False, null=True)),
                ('oc_gerencia', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=12, null=True)),
                ('clabe', models.CharField(blank=True, max_length=18, null=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_images')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.banco', unique=True)),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito')),
                ('staff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tipo_perfil')),
            ],
        ),
    ]
