# Generated by Django 3.2.5 on 2023-07-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='proveedores',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
