# Generated by Django 3.2.5 on 2023-08-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tipo_perfil_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
