# Generated by Django 4.2.4 on 2023-09-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_banco_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
