# Generated by Django 3.2.5 on 2023-04-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='almacen',
            field=models.ManyToManyField(null=True, related_name='almacenes', to='user.Almacen'),
        ),
    ]
