# Generated by Django 4.2.8 on 2024-02-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_banco_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
