# Generated by Django 3.2.5 on 2023-04-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='almacen',
            field=models.ManyToManyField(related_name='almacenes', to='user.Almacen'),
        ),
    ]
