# Generated by Django 4.2.8 on 2024-04-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='productos',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
