# Generated by Django 4.2.15 on 2024-09-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tipo_perfil_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='activos',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
