# Generated by Django 3.2.5 on 2023-06-14 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0004_auto_20230516_1804'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_unidad', models.CharField(max_length=50, null=True, unique=True)),
                ('serie', models.CharField(max_length=20, null=True)),
                ('cuenta_contable', models.CharField(max_length=20, null=True)),
                ('factura_interna', models.CharField(max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creado_por', to='user.profile')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('tipo_activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.tipo_activo')),
            ],
        ),
    ]
