# Generated by Django 3.2.5 on 2023-08-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_articulosordenados_comentario'),
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.marca'),
        ),
        migrations.AddField(
            model_name='activo',
            name='modelo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
