# Generated by Django 4.2.15 on 2024-09-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_auto_20230808_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus_Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
