# Generated by Django 4.2.15 on 2024-09-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_activo_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.estatus_activo'),
        ),
    ]
