# Generated by Django 4.2.15 on 2024-09-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_alter_activo_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='estatus',
        ),
    ]
