# Generated by Django 4.2.15 on 2024-09-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_activo_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
