# Generated by Django 4.2.15 on 2024-09-24 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_activo_fecha_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='factura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_activos', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='activo',
            name='factura_xml',
            field=models.FileField(blank=True, null=True, upload_to='xml_activos', validators=[django.core.validators.FileExtensionValidator(['xml'])]),
        ),
    ]
