# Generated by Django 4.2.15 on 2024-09-24 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_activo_factura_pdf_activo_factura_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='documento_baja',
            field=models.FileField(blank=True, null=True, upload_to='bajas_activos', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
