# Generated by Django 4.2.15 on 2024-09-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_activo_documento_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='serie',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
