# Generated by Django 4.2.15 on 2024-09-25 18:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_tipo_perfil_activos'),
        ('dashboard', '0024_historicalproduct_caducidad_product_caducidad'),
        ('activos', '0012_alter_activo_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='modified_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to='user.profile'),
        ),
        migrations.CreateModel(
            name='HistoricalActivo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('eco_unidad', models.CharField(db_index=True, max_length=50, null=True)),
                ('serie', models.CharField(db_index=True, max_length=20, null=True)),
                ('cuenta_contable', models.CharField(max_length=20, null=True)),
                ('factura_interna', models.CharField(max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=30, null=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('factura_pdf', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('factura_xml', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('documento_baja', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('modified_at', models.DateField(null=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.inventario')),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('estatus', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='activos.estatus_activo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.marca')),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('tipo_activo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='activos.tipo_activo')),
            ],
            options={
                'verbose_name': 'historical activo',
                'verbose_name_plural': 'historical activos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
