# Generated by Django 3.2.5 on 2023-04-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='deposito_colaborador',
            new_name='deposito_comprador',
        ),
        migrations.RenameField(
            model_name='historicalcompra',
            old_name='deposito_colaborador',
            new_name='deposito_comprador',
        ),
    ]
