# Generated by Django 3.2.5 on 2023-04-04 00:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20230403_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='factura_pdf',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='factura_xml',
        ),
        migrations.RemoveField(
            model_name='historicalcompra',
            name='factura_pdf',
        ),
        migrations.RemoveField(
            model_name='historicalcompra',
            name='factura_xml',
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subido', models.DateField(blank=True, null=True)),
                ('hora_subido', models.TimeField(blank=True, null=True)),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('hecho', models.BooleanField(default=False)),
                ('factura_pdf', models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('factura_xml', models.FileField(blank=True, null=True, upload_to='xml', validators=[django.core.validators.FileExtensionValidator(['xml'])])),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
            ],
        ),
    ]
