# Generated by Django 3.2.5 on 2023-05-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20230425_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
