# Generated by Django 3.2.5 on 2022-05-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20220506_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocomprado',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
