# Generated by Django 3.2.5 on 2023-05-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20230501_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='solo_servicios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='solo_servicios',
            field=models.BooleanField(default=False),
        ),
    ]
