# Generated by Django 3.2.5 on 2022-05-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20220506_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
