# Generated by Django 3.2.5 on 2022-05-06 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tipo_perfil_crear_sol'),
        ('compras', '0005_auto_20220506_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor_completo',
            name='distrito',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.distrito'),
        ),
        migrations.RemoveField(
            model_name='proveedor_completo',
            name='distrito',
        ),
        migrations.AddField(
            model_name='proveedor_completo',
            name='distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.distrito'),
        ),
    ]
