# Generated by Django 3.2.5 on 2022-05-06 23:01

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20220506_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='anticipo',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='anticipo',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
