# Generated by Django 3.2.5 on 2023-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20230511_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocomprado',
            name='cantidad_pendiente',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='cantidad_pendiente',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
