# Generated by Django 3.2.5 on 2023-05-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_auto_20230512_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='regresar_oc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='regresar_oc',
            field=models.BooleanField(default=False),
        ),
    ]
