# Generated by Django 3.2.5 on 2022-05-06 23:19

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20220506_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocomprado',
            name='precio_unitario',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='precio_unitario',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
