# Generated by Django 3.2.5 on 2023-06-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20230601_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
