# Generated by Django 3.2.5 on 2023-06-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_auto_20230602_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='opciones_condiciones',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='opciones_condiciones',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
