# Generated by Django 3.2.5 on 2023-07-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_auto_20230627_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProveedor_direcciones',
        ),
    ]
