# Generated by Django 3.2.5 on 2022-05-07 01:05

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_auto_20220506_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='oc_autorpor',
            new_name='oc_autorizada_por',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='oc_autorpor2',
            new_name='oc_autorizada_por2',
        ),
        migrations.RenameField(
            model_name='historicalcompra',
            old_name='oc_autorpor',
            new_name='oc_autorizada_por',
        ),
        migrations.RenameField(
            model_name='historicalcompra',
            old_name='oc_autorpor2',
            new_name='oc_autorizada_por2',
        ),
        migrations.AlterField(
            model_name='articulocomprado',
            name='precio_unitario_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='compra',
            name='anticipo_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='compra',
            name='costo_fletes_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='compra',
            name='impuestos_adicionales_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='compra',
            name='otros_pagos_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipo_de_cambio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='precio_unitario_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='anticipo_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='costo_fletes_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='impuestos_adicionales_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='otros_pagos_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='tipo_de_cambio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
    ]
