# Generated by Django 3.2.5 on 2023-07-04 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_historicalproveedor_direcciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='modified',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
