# Generated by Django 3.2.5 on 2023-07-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_auto_20230703_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='email_opt',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='email_opt',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
