# Generated by Django 3.2.5 on 2023-07-06 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20230622_1434'),
        ('user', '0001_initial'),
        ('compras', '0015_auto_20230703_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completo', models.BooleanField(default=False)),
                ('comentarios', models.TextField(max_length=100, null=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Comparativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, null=True)),
                ('marca', models.CharField(max_length=100, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('modelo2', models.CharField(blank=True, max_length=100, null=True)),
                ('marca2', models.CharField(blank=True, max_length=100, null=True)),
                ('precio2', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('modelo3', models.CharField(blank=True, max_length=100, null=True)),
                ('marca3', models.CharField(blank=True, max_length=100, null=True)),
                ('precio3', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completo', models.BooleanField(default=False)),
                ('comparativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.comparativo')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor_direcciones')),
                ('proveedor2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor2', to='compras.proveedor_direcciones')),
                ('proveedor3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor3', to='compras.proveedor_direcciones')),
            ],
        ),
    ]
