# Generated by Django 3.2.5 on 2022-05-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_auto_20220507_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tesoreria_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='tesoreria_local',
            field=models.BooleanField(default=True),
        ),
    ]
