# Generated by Django 3.2.5 on 2022-05-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_auto_20220507_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='flete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='flete',
            field=models.BooleanField(default=False),
        ),
    ]
