# Generated by Django 3.2.5 on 2023-07-06 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_comparativo_item_comparativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='comparativo',
        ),
        migrations.RemoveField(
            model_name='historicalcompra',
            name='comparativo',
        ),
    ]
