# Generated by Django 3.2.5 on 2022-05-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0013_auto_20220502_1308'),
        ('compras', '0018_auto_20220510_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocomprado',
            name='producto',
            field=models.ForeignKey(default='---', null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.articulosrequisitados'),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, default='---', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requisiciones.articulosrequisitados'),
        ),
    ]
