# Generated by Django 3.2.5 on 2023-07-13 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_auto_20230710_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_comparativo',
            name='cotizacion',
            field=models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='item_comparativo',
            name='cotizacion2',
            field=models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='item_comparativo',
            name='cotizacion3',
            field=models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
