# Generated by Django 3.2.5 on 2022-05-12 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0013_auto_20220502_1308'),
        ('compras', '0019_auto_20220510_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='impuesto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='impuesto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articulocomprado',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='requisiciones.articulosrequisitados'),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requisiciones.articulosrequisitados'),
        ),
    ]
