# Generated by Django 3.2.5 on 2023-07-16 03:22

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('compras', '0020_auto_20230712_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile'),
        ),
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='modificado_fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='telefono',
            field=phone_field.models.PhoneField(help_text='Número de contacto', max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Des_proveedores', to='user.profile'),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='modificado_fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='telefono',
            field=phone_field.models.PhoneField(help_text='Número de contacto', max_length=31, null=True),
        ),
    ]
