# Generated by Django 3.2.5 on 2022-05-13 23:38

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0021_auto_20220513_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocomprado',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulocomprado',
            name='precio_unitario',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='precio_unitario',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
