# Generated by Django 3.2.5 on 2023-07-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0021_auto_20230715_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='enviado_fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='enviado_fecha',
            field=models.DateField(null=True),
        ),
    ]
