# Generated by Django 3.2.5 on 2023-07-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0022_auto_20230715_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproveedor_direcciones',
            name='email_opt',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_direcciones',
            name='email_opt',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
