# Generated by Django 3.2.5 on 2022-05-16 22:09

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0023_auto_20220516_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='anticipo_currency',
            new_name='monto_anticipo_currency',
        ),
        migrations.RenameField(
            model_name='historicalcompra',
            old_name='anticipo_currency',
            new_name='monto_anticipo_currency',
        ),
        migrations.AddField(
            model_name='compra',
            name='monto_anticipo',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='monto_anticipo',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='anticipo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='anticipo',
            field=models.BooleanField(default=False),
        ),
    ]
