# Generated by Django 3.2.5 on 2023-07-30 04:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0024_auto_20230727_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_comparativo',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='item_comparativo',
            name='cotizacion2',
        ),
        migrations.RemoveField(
            model_name='item_comparativo',
            name='cotizacion3',
        ),
        migrations.RemoveField(
            model_name='item_comparativo',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='item_comparativo',
            name='proveedor2',
        ),
        migrations.RemoveField(
            model_name='item_comparativo',
            name='proveedor3',
        ),
        migrations.AddField(
            model_name='comparativo',
            name='cotizacion',
            field=models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='comparativo',
            name='cotizacion2',
            field=models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='comparativo',
            name='cotizacion3',
            field=models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='comparativo',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor_direcciones'),
        ),
        migrations.AddField(
            model_name='comparativo',
            name='proveedor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor2', to='compras.proveedor_direcciones'),
        ),
        migrations.AddField(
            model_name='comparativo',
            name='proveedor3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor3', to='compras.proveedor_direcciones'),
        ),
        migrations.AddField(
            model_name='item_comparativo',
            name='dias_de_entrega',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_comparativo',
            name='dias_de_entrega2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_comparativo',
            name='dias_de_entrega3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
