# Generated by Django 3.2.5 on 2023-08-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0025_auto_20230729_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_comparativo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item_comparativo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
