# Generated by Django 3.2.5 on 2022-05-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0025_auto_20220516_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCompra',
        ),
    ]
