# Generated by Django 3.2.5 on 2023-08-18 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20230810_1722'),
        ('compras', '0026_auto_20230802_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproveedor',
            name='familia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.familia'),
        ),
        migrations.AddField(
            model_name='historicalproveedor_direcciones',
            name='swift',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.familia'),
        ),
        migrations.AddField(
            model_name='proveedor_direcciones',
            name='swift',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
