# Generated by Django 3.2.5 on 2022-05-17 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0013_auto_20220502_1308'),
        ('user', '0007_tipo_perfil_crear_sol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0026_delete_historicalcompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCompra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('autorizado', models.BooleanField(default=None, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False)),
                ('cond_de_pago', models.CharField(choices=[('CR', 'Crédito'), ('CO', 'Contado')], default='CO', max_length=7)),
                ('dias_de_credito', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_de_cambio_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3)),
                ('tipo_de_cambio', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True)),
                ('anticipo', models.BooleanField(default=False)),
                ('monto_anticipo_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3)),
                ('monto_anticipo', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dias_de_entrega', models.PositiveIntegerField(null=True)),
                ('impuesto', models.BooleanField(default=False)),
                ('impuestos_adicionales_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3)),
                ('impuestos_adicionales', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('otros_pagos_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3)),
                ('otros_pagos', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('flete', models.BooleanField(default=False)),
                ('costo_fletes_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3)),
                ('costo_fletes', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tesoreria_local', models.BooleanField(default=True)),
                ('opciones_condiciones', models.CharField(max_length=250, null=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creada_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oc_autorizada_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('oc_autorizada_por2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.profile')),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.proveedor_completo')),
                ('req', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='requisiciones.requis')),
                ('uso_del_cfdi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.uso_cfdi')),
            ],
            options={
                'verbose_name': 'historical compra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
