# Generated by Django 3.2.5 on 2023-08-21 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0027_auto_20230818_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor_direcciones',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.estado'),
        ),
    ]
