# Generated by Django 3.2.5 on 2022-05-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0027_historicalcompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='anticipo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='anticipo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
