# Generated by Django 3.2.5 on 2023-08-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0028_alter_proveedor_direcciones_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproveedor_direcciones',
            name='swift',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor_direcciones',
            name='swift',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
