# Generated by Django 3.2.5 on 2022-05-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0028_auto_20220516_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='anticipo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='anticipo',
            field=models.BooleanField(default=False),
        ),
    ]
