# Generated by Django 3.2.5 on 2022-05-17 01:12

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0029_auto_20220516_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='costo_fletes',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='costo_fletes_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='compra',
            name='impuestos_adicionales',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='impuestos_adicionales_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='compra',
            name='monto_anticipo',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='monto_anticipo_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='compra',
            name='opciones_condiciones',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='otros_pagos',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='otros_pagos_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='costo_fletes',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='costo_fletes_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='impuestos_adicionales',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='impuestos_adicionales_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='monto_anticipo',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='monto_anticipo_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='opciones_condiciones',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='otros_pagos',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='otros_pagos_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
    ]
