# Generated by Django 4.2.4 on 2023-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0029_auto_20230824_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalarticulocomprado',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical articulo comprado', 'verbose_name_plural': 'historical articulo comprados'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompra',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical compra', 'verbose_name_plural': 'historical compras'},
        ),
        migrations.AlterModelOptions(
            name='historicalproveedor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical proveedor', 'verbose_name_plural': 'historical proveedors'},
        ),
        migrations.AlterModelOptions(
            name='historicalproveedor_direcciones',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical proveedor_direcciones', 'verbose_name_plural': 'historical proveedor_direccioness'},
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproveedor_direcciones',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
