# Generated by Django 3.2.5 on 2022-05-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0030_auto_20220516_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='dias_de_entrega',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='dias_de_entrega',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
