# Generated by Django 4.2.4 on 2023-09-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0030_alter_historicalarticulocomprado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativo',
            name='comentarios',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
