# Generated by Django 5.0.1 on 2024-02-07 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0030_tipo_proceso_alter_proveedor_direcciones_nombre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Proceso',
            new_name='Tipo_Evaluacion',
        ),
        migrations.RenameField(
            model_name='historicalpreevaluacion',
            old_name='tipo_proceso',
            new_name='tipo_evaluacion',
        ),
        migrations.RenameField(
            model_name='preevaluacion',
            old_name='tipo_proceso',
            new_name='tipo_evaluacion',
        ),
        migrations.AlterField(
            model_name='proveedor_direcciones',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
    ]
