# Generated by Django 3.2.5 on 2022-05-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0031_auto_20220516_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cond_de_pago',
            field=models.CharField(choices=[('CO', 'Contado'), ('CR', 'Crédito')], default='CO', max_length=7),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='cond_de_pago',
            field=models.CharField(choices=[('CO', 'Contado'), ('CR', 'Crédito')], default='CO', max_length=7),
        ),
    ]
