# Generated by Django 5.0.1 on 2024-02-13 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0031_rename_tipo_proceso_tipo_evaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreevaluacion',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preevaluacion',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preevaluacion',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preevaluacion', to='compras.proveedor'),
        ),
    ]
