# Generated by Django 3.2.5 on 2022-05-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0033_auto_20220516_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor_completo'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='uso_del_cfdi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.uso_cfdi'),
        ),
    ]
