# Generated by Django 5.0.1 on 2024-02-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0034_alter_historicalpreevaluacion_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpreevaluacion',
            name='resultado',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='preevaluacion',
            name='resultado',
            field=models.BooleanField(default=None),
        ),
    ]
