# Generated by Django 5.0.1 on 2024-02-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0035_alter_historicalpreevaluacion_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpreevaluacion',
            name='resultado',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='preevaluacion',
            name='resultado',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
