# Generated by Django 4.2.9 on 2024-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0036_alter_historicalpreevaluacion_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='recepcion_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='recepcion_completa',
            field=models.BooleanField(default=False),
        ),
    ]
