# Generated by Django 3.2.5 on 2022-05-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0036_auto_20220523_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='tesoreria_local',
        ),
        migrations.RemoveField(
            model_name='historicalcompra',
            name='tesoreria_local',
        ),
        migrations.AddField(
            model_name='compra',
            name='tesoreria_matriz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='tesoreria_matriz',
            field=models.BooleanField(default=False),
        ),
    ]
