# Generated by Django 3.2.5 on 2022-05-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0037_auto_20220524_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='autorizado1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='autorizado2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='autorizado1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='autorizado2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
