# Generated by Django 3.2.5 on 2022-05-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0038_auto_20220530_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='factura_pdf',
            field=models.FileField(blank=True, upload_to='facturas'),
        ),
        migrations.AddField(
            model_name='compra',
            name='factura_xml',
            field=models.FileField(blank=True, null=True, upload_to='xml'),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='factura_pdf',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='factura_xml',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
