# Generated by Django 4.2.9 on 2024-03-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0030_alter_estatus_proveedor_nombre'),
        ('compras', '0038_articulocomprado_recepcion_completa_and_more'),
    ]

    operations = [
    ]
