# Generated by Django 4.2.8 on 2024-03-27 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisiciones', '0012_alter_historicalarticulosrequisitados_options_and_more'),
        ('compras', '0039_merge_20240325_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='requisiciones.requis'),
        ),
    ]
