# Generated by Django 4.2.9 on 2024-05-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0040_alter_compra_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_comparativo',
            name='comparativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_comparativos', to='compras.comparativo'),
        ),
        migrations.AlterField(
            model_name='preevaluacion',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preevaluaciones', to='compras.proveedor'),
        ),
    ]
