# Generated by Django 3.2.5 on 2022-05-31 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0040_auto_20220530_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='factura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='factura_pdf',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
