# Generated by Django 3.2.5 on 2022-05-31 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0041_auto_20220531_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='factura_xml',
            field=models.FileField(blank=True, null=True, upload_to='xml', validators=[django.core.validators.FileExtensionValidator(['xml'])]),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='factura_xml',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['xml'])]),
        ),
    ]
