# Generated by Django 4.2.9 on 2024-08-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0041_alter_item_comparativo_comparativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comentario_gerencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='comentario_gerencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
