# Generated by Django 3.2.5 on 2022-05-31 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0042_auto_20220531_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='created_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='created_at',
            field=models.DateField(blank=True, editable=False),
        ),
    ]
