# Generated by Django 4.2.15 on 2024-09-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0043_historicalpreevaluacion_eval_actividades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preevaluacion',
            name='comparativo_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preevaluaciones_comparativo', to='compras.comparativo'),
        ),
    ]
