# Generated by Django 5.2.4 on 2026-02-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0044_alter_preevaluacion_comparativo_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparativo',
            name='comentarios',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='comentarios',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='comentarios',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
