# Generated by Django 3.2.5 on 2022-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0044_auto_20220601_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='autorizado',
        ),
        migrations.RemoveField(
            model_name='historicalcompra',
            name='autorizado',
        ),
        migrations.AddField(
            model_name='compra',
            name='autorizado_date1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='autorizado_date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='autorizado_date1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='autorizado_date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='autorizado1',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='autorizado2',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='autorizado1',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='autorizado2',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
