# Generated by Django 3.2.5 on 2022-06-03 00:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0045_auto_20220601_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicalcompra',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='compra',
            name='autorizado_hora1',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='autorizado_hora2',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='autorizado_hora1',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 6, 3, 0, 29, 5, 331024, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='autorizado_hora2',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='autorizado_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='autorizado_date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='autorizado_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='autorizado_date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
