# Generated by Django 5.2.4 on 2026-02-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0045_alter_comparativo_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='opciones_condiciones',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='opciones_condiciones',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
