# Generated by Django 5.2.4 on 2026-02-19 23:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0046_alter_compra_opciones_condiciones_and_more'),
        ('user', '0008_historicalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidencias', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'png', 'jpg', 'jpeg'))])),
                ('uploaded', models.DateField()),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('hecho', models.BooleanField(default=False)),
                ('oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='compras.compra')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
