# Generated by Django 3.2.5 on 2022-06-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0046_auto_20220602_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
