# Generated by Django 3.2.5 on 2022-06-08 16:16

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0047_auto_20220606_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='monto_pagado',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='monto_pagado_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='monto_pagado',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='monto_pagado_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
    ]
