# Generated by Django 3.2.5 on 2022-06-08 16:22

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0049_auto_20220608_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='monto_pagado',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='monto_pagado',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MXN', max_digits=14),
        ),
    ]
