# Generated by Django 3.2.5 on 2022-06-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0050_auto_20220608_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='entrada_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='entrada_completa',
            field=models.BooleanField(default=False),
        ),
    ]
