# Generated by Django 3.2.5 on 2022-06-14 20:13

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0051_auto_20220613_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocomprado',
            name='precio_unitario',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='articulocomprado',
            name='precio_unitario_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='precio_unitario',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='precio_unitario_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
    ]
