# Generated by Django 3.2.5 on 2022-07-07 23:31

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0053_auto_20220705_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tipo_de_cambio',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='MXN', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='tipo_de_cambio',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='MXN', max_digits=14, null=True),
        ),
    ]
