# Generated by Django 3.2.5 on 2022-07-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0056_auto_20220714_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulocomprado',
            name='entradas_pendientes',
        ),
        migrations.RemoveField(
            model_name='historicalarticulocomprado',
            name='entradas_pendientes',
        ),
        migrations.AddField(
            model_name='articulocomprado',
            name='entradas_completas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalarticulocomprado',
            name='entradas_completas',
            field=models.BooleanField(default=False),
        ),
    ]
