# Generated by Django 3.2.5 on 2022-07-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0057_auto_20220715_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulocomprado',
            old_name='entradas_completas',
            new_name='entrada_completa',
        ),
        migrations.RenameField(
            model_name='historicalarticulocomprado',
            old_name='entradas_completas',
            new_name='entrada_completa',
        ),
    ]
