# Generated by Django 3.2.5 on 2022-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0058_auto_20220715_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulocomprado',
            name='cantidad_pendiente',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticulocomprado',
            name='cantidad_pendiente',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
