# Generated by Django 3.2.5 on 2022-07-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0059_auto_20220715_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='folio',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompra',
            name='folio',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
