# Generated by Django 3.2.5 on 2022-07-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0061_auto_20220721_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulocomprado',
            name='seleccionado',
        ),
        migrations.RemoveField(
            model_name='historicalarticulocomprado',
            name='seleccionado',
        ),
    ]
