# Generated by Django 3.2.5 on 2022-08-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0062_auto_20220721_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='autorizado_hora1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='autorizado_hora2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='autorizado_hora1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='autorizado_hora2',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
