# Generated by Django 3.2.5 on 2023-03-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo_gasto',
            old_name='concepto',
            new_name='comentario',
        ),
    ]
