# Generated by Django 3.2.5 on 2023-04-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asignado_gasto', to='user.profile'),
        ),
    ]
