# Generated by Django 3.2.5 on 2023-04-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_solicitud_gasto_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='impuestos_retenidos',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='articulo_gasto',
            name='otros_impuestos',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True),
        ),
    ]
