# Generated by Django 3.2.5 on 2023-03-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_rename_concepto_articulo_gasto_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_gasto',
            name='impuestos_retenidos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='articulo_gasto',
            name='otros_impuestos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='articulo_gasto',
            name='comentario',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
