# Generated by Django 3.2.5 on 2023-03-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_auto_20230326_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_gasto',
            name='entrada_salida_express',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
