# Generated by Django 3.2.5 on 2023-05-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_auto_20230428_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo_gasto',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
    ]
