# Generated by Django 3.2.5 on 2023-05-14 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230511_1401'),
        ('user', '0001_initial'),
        ('gastos', '0004_auto_20230502_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada_Gasto_Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completado_fecha', models.DateField(null=True)),
                ('completado_hora', models.TimeField(null=True)),
                ('completo', models.BooleanField(default=False)),
                ('comentario', models.TextField(max_length=200, null=True)),
                ('almacenista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.solicitud_gasto')),
            ],
        ),
        migrations.CreateModel(
            name='Conceptos_Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=14, null=True)),
                ('agotado', models.BooleanField(default=False)),
                ('concepto_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario')),
                ('entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.entrada_gasto_ajuste')),
            ],
        ),
    ]
