# Generated by Django 3.2.5 on 2023-03-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_articulo_gasto_entrada_salida_express'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='cantidad',
            field=models.DecimalField(decimal_places=6, max_digits=6, null=True),
        ),
    ]
