# Generated by Django 3.2.5 on 2023-03-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_alter_articulo_gasto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
    ]
