# Generated by Django 3.2.5 on 2023-06-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_conceptos_entradas_entrada_gasto_ajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_gasto',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='articulo_gasto',
            name='validacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conceptos_entradas',
            name='comentario',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conceptos_entradas',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud_gasto',
            name='facturas_completas',
            field=models.BooleanField(default=False),
        ),
    ]
