# Generated by Django 3.2.5 on 2023-03-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_alter_articulo_gasto_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='cantidad',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='articulo_gasto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True),
        ),
    ]
