# Generated by Django 4.2.4 on 2023-09-08 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_auto_20230810_1737'),
        ('gastos', '0008_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_gasto',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.proyecto'),
        ),
        migrations.AddField(
            model_name='articulo_gasto',
            name='subproyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.subproyecto'),
        ),
    ]
