# Generated by Django 3.2.5 on 2023-03-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_auto_20230326_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
