# Generated by Django 4.2.4 on 2023-09-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_articulo_gasto_proyecto_articulo_gasto_subproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_gasto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='solicitud_gasto',
            name='subproyecto',
        ),
    ]
