# Generated by Django 4.2.4 on 2023-10-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0012_alter_articulo_gasto_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='gasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.solicitud_gasto'),
        ),
    ]
