# Generated by Django 4.2.8 on 2024-04-03 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0014_alter_articulo_gasto_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='gasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='gastos.solicitud_gasto'),
        ),
    ]
