# Generated by Django 4.2.8 on 2024-06-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_historicalproduct_porcentaje_and_more'),
        ('gastos', '0015_alter_articulo_gasto_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_gasto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventario'),
        ),
    ]
