# Generated by Django 4.2.9 on 2024-06-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0016_alter_articulo_gasto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='comentarios',
            field=models.TextField(null=True),
        ),
    ]
