# Generated by Django 4.2.9 on 2024-06-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tipo_perfil_productos'),
        ('gastos', '0017_solicitud_gasto_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_gasto',
            name='autorizado_por2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='user.profile'),
        ),
    ]
