# Generated by Django 4.2.9 on 2024-06-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0018_solicitud_gasto_autorizado_por2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_gasto',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
