# Generated by Django 5.2.4 on 2026-03-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0019_alter_solicitud_gasto_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_timbrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
    ]
