# Generated by Django 5.2.4 on 2026-03-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0020_factura_fecha_timbrado_factura_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
